# Generated by Django 2.1.5 on 2019-03-02 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='endDate',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='project',
            name='startDate',
            field=models.CharField(max_length=30),
        ),
    ]
