# Generated by Django 2.1.5 on 2019-03-02 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0003_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='finalSelection',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
