# Generated by Django 2.1.5 on 2019-03-02 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0005_freelancer_numberofproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancer',
            name='paytmLink',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
