# Generated by Django 2.1.5 on 2019-03-04 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0006_freelancer_paytmlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='freelancerTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memberName', models.CharField(max_length=50)),
                ('experience', models.IntegerField()),
                ('mobileNo', models.IntegerField()),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employer.freelancer')),
            ],
        ),
    ]
