# Generated by Django 2.1.5 on 2019-03-04 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0007_freelancerteam'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='team',
            field=models.CharField(default='No', max_length=20),
        ),
    ]
