# Generated by Django 2.1.5 on 2019-03-05 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0008_project_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='team',
            field=models.CharField(default='No', max_length=10),
        ),
    ]
