# Generated by Django 2.1.5 on 2019-03-14 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0009_bid_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=50)),
            ],
        ),
    ]
