# Generated by Django 2.1.5 on 2019-04-04 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0012_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='employers',
            name='Money',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='Money',
            field=models.IntegerField(default=0),
        ),
    ]
