# Generated by Django 2.1.5 on 2019-04-05 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0013_auto_20190404_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancerteam',
            name='dept',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
